# Generated by Django 5.1 on 2024-09-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pensioner', 'Pensioner'), ('payroll_officer', 'Payroll Officer')], default='admin', max_length=20),
        ),
    ]
