# Generated by Django 5.1 on 2024-09-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrations', '0001_initial'),
        ('pensioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='pensioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_histories', to='pensioners.pensioner'),
        ),
        migrations.AddField(
            model_name='pensionplan',
            name='pension_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pension_plans', to='administrations.pensionscheme'),
        ),
        migrations.AddField(
            model_name='pensioner',
            name='pension_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pensioners', to='pensioners.pensionplan'),
        ),
    ]
