# Generated by Django 5.1 on 2024-09-04 12:18

import pensioners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensioners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pensioner',
            name='pension_id',
            field=models.CharField(default=pensioners.models.generate_pension_id, editable=False, max_length=20, unique=True),
        ),
    ]
