# Generated by Django 5.1 on 2024-09-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensioners', '0004_alter_pensioner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensioner',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=10),
        ),
    ]
