# Generated by Django 5.1 on 2024-09-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('pensioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='pensioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensioners.pensioner'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pensioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensioners.pensioner'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payroll'),
        ),
    ]
